/*
 * Copyright (c) 1993-1995 by Argonaut Technologies Limited. All rights reserved.
 *
 * $Id: brv1db.h 2.1 1996/03/01 18:48:16 sam Exp $
 * $Locker:  $
 *
 * Master include file for BRender V1 Database
 *
 */
#ifndef _BRV1DB_H_
#define _BRV1DB_H_

#ifdef __cplusplus
	extern "C" {
#endif

#ifndef _MATERIAL_H_
#include "material.h"
#endif

#ifndef _MODEL_H_
#include "model.h"
#endif

#ifndef _ACTOR_H_
#include "actor.h"
#endif

#ifndef _CAMERA_H_
#include "camera.h"
#endif

#ifndef _LIGHT_H_
#include "light.h"
#endif

#ifndef _FMT_H_
#include "fmt.h"
#endif

#ifndef _NO_PROTOTYPES
#ifndef _V1DB_P_H_
#include "v1db_p.h"
#endif
#endif

#ifdef __cplusplus
};
#endif
#endif

